# Generated by Django 4.2.7 on 2023-11-25 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amkosi',
            fields=[
                ('assoc_name', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('assoc_email', models.CharField(max_length=30)),
                ('assoc_password', models.CharField(max_length=128, unique=True)),
                ('location', models.CharField(max_length=12)),
                ('assoc_phone_no', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='FarmDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('owner_of_farm', models.CharField(max_length=15)),
                ('size_of_farm', models.CharField(max_length=10)),
                ('no_of_farms', models.DecimalField(decimal_places=0, max_digits=20)),
                ('assets_available', models.CharField(max_length=15)),
                ('physical_location', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Farmers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('farmer_name', models.CharField(max_length=15)),
                ('bank_name', models.CharField(max_length=15)),
                ('bank_account', models.DecimalField(decimal_places=0, max_digits=10)),
                ('type_of_crops', models.CharField(max_length=25)),
                ('quant_of_products', models.FloatField()),
                ('total_cost_production', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=30)),
                ('phone_no', models.CharField(max_length=13)),
                ('location', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Crops',
            fields=[
                ('crop_id', models.AutoField(primary_key=True, serialize=False)),
                ('crop_name', models.CharField(max_length=30)),
                ('quant_of_crops', models.IntegerField()),
                ('crop_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.farmers')),
            ],
        ),
    ]
