# Generated by Django 4.2.7 on 2023-11-25 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmers',
            name='year',
            field=models.IntegerField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
