# Generated by Django 4.2.7 on 2023-11-25 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_farmers_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmers',
            name='year',
            field=models.IntegerField(),
        ),
    ]
